---
language: python
services: docker

env:
  - MOLECULE_NO_LOG="false"
  global:
    - ROLE_NAME: ansible-role-strongswan-swanctl
  matrix:
#    - MOLECULE_DISTRO: centos8
    - MOLECULE_DISTRO: centos7
      MOLECULE_PLAYBOOK: playbook-source-install.yml
    - MOLECULE_DISTRO: ubuntu1804
    - MOLECULE_DISTRO: ubuntu1604
    - MOLECULE_DISTRO: debian10

install:
  # Install test dependencies.
  - pip install molecule docker

before_script:
  # Use actual Ansible Galaxy role name for the project directory.
  - cd ../
  - mv $ROLE_NAME hybridadmin.$ROLE_NAME
  - cd hybridadmin.$ROLE_NAME

script:
  # Run tests.
  - molecule --debug test

notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
