---
language: python
python: "2.7"
sudo: required
services:
  - docker

before_install:
  - docker --version
install:
  - pip install molecule docker==4.1.0
  # Install Ansible.
  - "pip install ansible"

  # Add ansible.cfg to pick up roles path.
  - "{ echo '[defaults]'; echo 'roles_path = ../'; } >> ansible.cfg"

  # Install Ansible Galaxy Roles
  - "ansible-galaxy install -r requirements.yml --force"
script:
  - molecule test --all
