---
- src: https://github.com/hybridadmin/ansible-role-strongswan-swanctl
  version: master
  name: ansible-role-strongswan-swanctl
- src: geerlingguy.repo-epel
#- src: geerlingguy.certbot
- src: https://github.com/geerlingguy/ansible-role-certbot.git
  version: master
  name: geerlingguy.certbot
- src: shhirose.firewalld
