---

- name: Copy certificate from server to localhost
  fetch:
    src: "{{ item }}"
    dest: certs/
    flat: true
  with_items:
    - "{{ strongswan_swanctl_config_dir }}/x509ca/strongswanCert.pem"
    - "{{ strongswan_swanctl_config_dir }}/x509/Cert.pem"
