---
- block:
  - name: Redhat | Enable EPEL rpm repo
    yum:
      name: epel-release
      state: present
  
  - name: Redhat | Install Strongswan package
    yum:
      name: strongswan
      state: present
when: ansible_facts['os_family'] == "RedHat"

- block:
  - name: Debian | Install Strongswan package
    apt:
      pkg:
      - strongswan
      - strongswan-swanctl 
      - apparmor-utils
      - debconf-utils
when: ansible_facts['os_family'] == "Debian"
