---
- name: process strongswan pre-requisites
  block:
  - name: Redhat | enable EPEL repo
    become: true
    package:
      name: epel-release
      state: present
    when: ansible_os_family == 'RedHat'

  - name: Redhat | set required package list
    set_fact:
      package_list: ['strongswan']
    when: ansible_os_family == 'RedHat'

  - name: Redhat 8 | include dnf-plugins-core package
    set_fact:
      package_list: "{{ package_list + [ 'dnf-plugins-core' ] }}"
    when:
    - ansible_os_family == 'RedHat'
    - ansible_distribution_major_version  | int >= 8

  - name: Debian | set required package list
    set_fact:
      package_list: ['strongswan', 'strongswan-swanctl', 'libcharon-extra-plugins', 'apparmor-utils', 'debconf-utils', 'procps']
    when: ansible_os_family == 'Debian'

- name: Install required strongswan packages
  action: >
    {{ ansible_pkg_mgr }} name={{ package_list }} state=present update_cache=yes
    vars:
      packages: "{{ package_list }}"
  when: package_list is defined
