---

- name: Debian | strongswan-swanctl config directory
  set_fact:
    strongswan_swanctl_config_dir: /etc/swanctl
    strongswan_swanctl_svc: strongswan-swanctl.service
    strongswan_conf_file: "/etc/strongswan.d/10-strongswan.conf"
  when: ansible_facts['os_family'] == "Debian"

- name: RedHat | strongswan-swanctl config directory
  set_fact:
    strongswan_swanctl_config_dir: /etc/strongswan/swanctl
    strongswan_swanctl_svc: strongswan.service
    strongswan_conf_file: "/etc/strongswan/strongswan.d/10-strongswan.conf"
  when: ansible_facts['os_family'] == "RedHat"

- name: strongswan-swanctl config file
  set_fact:
    strongswan_swanctl_config_file: "{{ strongswan_swanctl_config_dir }}/swanctl.conf"
  when: strongswan_swanctl_config_dir is defined

- include: install.yml
  tags: strongswan-install

- include: download-cert.yml
  tags: strongswan-download-cert
  when: strongswan_client and strongswan_download_cert

- include: upload-cert.yml
  tags: strongswan-upload-cert
  when: strongswan_client and strongswan_upload_cert

- include: config.yml
  tags: strongswan-config
