---

- name: "Create PKI directories"
  file:
    path: "{{ item }}"
    state: directory
    mode: "0755"
  with_items:
    - "{{ ansible_user_dir }}/pki/private"
    - "{{ ansible_user_dir }}/pki/cacerts"
    - "{{ ansible_user_dir }}/pki/certs"

- name: "Generate CA root key"
  shell: |
    set -o pipefail
    ipsec pki --gen --type rsa --size 4096 --outform pem > {{ ansible_user_dir }}/pki/private/ca-key.pem
  args:
    executable: /bin/bash
    creates: "{{ ansible_user_dir }}/pki/private/ca-key.pem"

- name: "Create root certificate authority"
  shell: |
    set -o pipefail
    ipsec pki --self --ca --lifetime 3650 --in {{ ansible_user_dir }}/pki/private/ca-key.pem --type rsa \
    --dn "CN=VPN root CA" --outform pem > {{ ansible_user_dir }}/pki/cacerts/ca-cert.pem
  args:
    executable: /bin/bash
    creates: "{{ ansible_user_dir }}/pki/cacerts/ca-cert.pem"

- name: "Create VPN Server private key"
  shell: |
    set -o pipefail
    ipsec pki --gen --type rsa --size 4096 --outform pem > {{ ansible_user_dir }}/pki/private/server-key.pem
  args:
    executable: /bin/bash
    creates: "{{ ansible_user_dir }}/pki/private/server-key.pem"

- name: "Sign VPN server certificate"
  shell: |
    set -o pipefail
    ipsec pki --pub --in {{ ansible_user_dir }}/pki/private/server-key.pem \
       --type rsa | ipsec pki --issue --lifetime 1825 \
            --cacert {{ ansible_user_dir }}/pki/cacerts/ca-cert.pem \
            --cakey {{ ansible_user_dir }}/pki/private/ca-key.pem \
            --dn "CN={{ ansible_default_ipv4.address|default(ansible_all_ipv4_addresses[0]) }}" \
            --san "{{ ansible_default_ipv4.address|default(ansible_all_ipv4_addresses[0]) }}" \
            --flag serverAuth --flag ikeIntermediate --outform pem \
        >  {{ ansible_user_dir }}/pki/certs/server-cert.pem
  args:
    executable: /bin/bash
    creates: "{{ ansible_user_dir }}/pki/certs/server-cert.pem"

- name: Symlink PKI certificates
  file:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    owner: root
    group: root
    state: link
  with_items:
    - { src: "{{ ansible_user_dir }}/pki/private/server-key.pem", dest: "/etc/swanctl/private/server-key.pem" }
    - { src: "{{ ansible_user_dir }}/pki/certs/server-cert.pem", dest: "/etc/swanctl/x509/cert.pem" }
    - { src: "{{ ansible_user_dir }}/pki/cacerts/ca-cert.pem", dest: "/etc/swanctl/x509ca/ca-cert.pem" }
