---

- name: reboot
  import_tasks: reboot.yml

- name: swanctl restart
  systemd:
    name: "{{ strongswan_swanctl_svc }}"
    state: restarted

- name: sysctl reload
  command: sysctl -p "{{ sysctl_conf_file }}"
