---
- name: Converge
  hosts: all
  become: true

  vars:
    _system_packages:
      default:
        - git
      Debian:
        - cron
      RedHat:
        - cronie
    system_packages: "{{ _system_packages['default'] + _system_packages[ansible_os_family] }}"
    strongswan_letsencrypt_enable: false
    certbot_auto_renew_user: root
    certbot_certs:
      - email: janedoe@example.com
        domains:
          - vpn.example.com

  pre_tasks:
#    - name: Install system packages.
#      action: >
#        {{ ansible_pkg_mgr }} name={{ system_packages }} state=present update_cache=yes

    - name: "Include hybridadmin.strongswan role"
      include_role:
        name: "ansible-role-strongswan"
#        name: "hybridadmin.strongswan"
