---
- name: Converge
  hosts: all
  become: true

  vars:
    strongswan_letsencrypt_enable: false
#    certbot_auto_renew_user: root
#    certbot_certs:
#      - email: janedoe@example.com
#        domains:
#          - vpn.example.com

  pre_tasks:
    - name: Update apt cache.
      apt: update_cache=yes cache_valid_time=600
      when: ansible_os_family == 'Debian'
      changed_when: false

#    - name: Install cron (RedHat).
#      package: name="{{ item }}" state=present
#      with_items:
#        - cronie
#        - git
#      when: ansible_os_family == 'RedHat'

#    - name: Install cron (Debian).
#      package: name="{{ item }}" state=present
#      with_items:
#        - cron
#        - git
#      when: ansible_os_family == 'Debian'

    - name: "Include hybridadmin.strongswan_swanctl role"
      include_role:
        name: "ansible-role-strongswan-swanctl"
#        name: "hybridadmin.strongswan_swanctl"
