---
driver:
  name: docker
platforms:
  - name: ansible-role-strongswan-swanctl-debian-8
    image: debian:8

  - name: ansible-role-strongswan-swanctl-ubuntu-1404
    image: ubuntu:14.04

  - name: ansible-role-strongswan-swanctl-ubuntu-1604
    image: ubuntu:16.04

  - name: ansible-role-strongswan-swanctl-ubuntu-1804
    image: ubuntu:18.04

  - name: ansible-role-strongswan-swanctl-centos-7
    image: centos:7

#driver:
#  name: vagrant
#  provider:
#    name: virtualbox
#platforms:
#  - name: xenial64
#    box: bento/ubuntu-16.04

verifier:
  name: testinfra

lint:
  name: yamllint
  enabled: False

provisioner:
  name: ansible
  playbooks:
    create: ../resources/create.yml
    prepare: ../resources/prepare.yml
    converge: ../resources/playbook.yml
    destroy: ../resources/destroy.yml
  inventory:
    group_vars:
      all:
#        zsh_user: root
