---
- name: Converge
  hosts: all
  become: true
  no_log: result.rc == 0

  vars:
    certbot_auto_renew_user: root
    certbot_create_if_missing: yes
    
    certbot_certs:
     - email: atmchikomo@gmail.com
       domains:
         - "{{ inventory_hostname }}"
    
    certbot_create_standalone_stop_services: []

  pre_tasks:
    - name: Update apt cache.
      apt: update_cache=yes cache_valid_time=600
      when: ansible_os_family == 'Debian'
      changed_when: false

    - name: Install dependencies (RedHat).
      yum: name={{ item }} state=present
      when: ansible_os_family == 'RedHat'
      with_items:
        - cronie
        - epel-release

    - name: Install cron (Debian).
      apt: name=cron state=present
      when: ansible_os_family == 'Debian'

  roles:
    - ansible-role-strongswan-swanctl
