---
scenario:
  name: user
driver:
  name: docker
platforms:
  - name: ansible-role-strongswan-swanctl-ubuntu-1804
    image: ubuntu
    image_version: 18.04
    volume_mounts:
      - ${MOLECULE_APTPROXY_PATH}:/etc/apt/apt.conf.d/00aptproxy
  - name: ansible-role-strongswan-swanctl-centos-7
    image: centos
    image_version: 7

#driver:
#  name: vagrant
#vagrant:
#  platforms:
#    - name: xenial64
#      box: bento/ubuntu-16.04
#  providers:
#    - name: virtualbox
#      type: virtualbox
#  instances:
#    - name: vagrant-01

lint:
  name: yamllint
  enabled: False

provisioner:
  name: ansible
  playbooks:
    create: ../resources/create.yml
    prepare: prepare.yml
    converge: ../resources/playbook.yml
    destroy: ../resources/destroy.yml
  inventory:
    group_vars:
      all:
        certbot_auto_renew: false
#        zsh_user: testuser
